# Generated by Django 4.2.3 on 2023-07-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelucia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('coracao', models.BooleanField()),
                ('tamanho', models.CharField(max_length=2)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
